In [2]:
import numpy as np

# Create a random vector of size 15 with integers from 1 to 20
rv = np.random.randint(1, 21, size=15)

print(rv)


[20  8  9 14  3 11 16 19 20  3  2 18  2 13 16]


In [8]:
# Reshape it to a 3x5 array
ra = rv.reshape(3, 5)

print(ra)


[[20  8  9 14  3]
 [11 16 19 20  3]
 [ 2 18  2 13 16]]


In [7]:
# Shape of the array
print("Shape of the array:", ra.shape)

Shape of the array: (3, 5)


In [9]:
print("Original Array:\n", ra)

# Replace the max in each row with 0
for i in range(ra.shape[0]):
    max_index = ra[i].argmax()  # Find index of max in the row
    ra[i, max_index] = 0        # Replace max with 0

print("\nArray after replacing max in each row with 0:\n", ra)

Original Array:
 [[20  8  9 14  3]
 [11 16 19 20  3]
 [ 2 18  2 13 16]]

Array after replacing max in each row with 0:
 [[ 0  8  9 14  3]
 [11 16 19  0  3]
 [ 2  0  2 13 16]]


In [12]:
# Create a 4x3 array with 4-byte integer elements (int32)
array= np.random.randint(1, 101, size=(4, 3), dtype=np.int32)

# Print the array
print("Array:\n", array)

# Print shape, type, and data type
print("Shape:", array.shape)
print("Type:", type(array))
print("Data type:", array.dtype)


Array:
 [[58 95 29]
 [13 41 57]
 [50 56 62]
 [56 96  7]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [13]:
# Define the square matrix
A = np.array([[3, -2],
              [1,  0]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the results
print("Eigenvalues:", eigenvalues)


print("\nRight Eigenvectors (each column is an eigenvector):", eigenvectors)



Eigenvalues: [2. 1.]

Right Eigenvectors (each column is an eigenvector): [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [14]:
arr = np.array([[0, 1, 2],
                [3, 4, 5]])

# Extract the main diagonal
diagonal = np.diag(arr)

# Compute the sum of the diagonal elements
sum = np.sum(diagonal)

print("Diagonal elements:", diagonal)
print("Sum of diagonal elements:", sum)


Diagonal elements: [0 4]
Sum of diagonal elements: 4


In [15]:
# Original 3x2 array
array = np.array([[1, 2],
                           [3, 4],
                           [5, 6]])

print("Original 3x2 Array:\n", array)

# Reshape to 2x3
r_array = array.reshape(2, 3)

print("\nReshaped 2x3 Array:\n", r_array)


Original 3x2 Array:
 [[1 2]
 [3 4]
 [5 6]]

Reshaped 2x3 Array:
 [[1 2 3]
 [4 5 6]]
